FROM node:24-bookworm

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
 git \
 libimobiledevice-dev \
 libimobiledevice-utils \
 libplist-dev \
 libssl-dev \
 usbmuxd \
 vim



# Set the entrypoint to launch a Bash shell
ENTRYPOINT ["/bin/bash"]

