FROM node:20-bookworm

# Set environment variables to avoid interactive prompts
ENV DEBIAN_FRONTEND=noninteractive

# Set PYTHON environment variable for node-gyp
ENV PYTHON=/usr/bin/python3

# Install required packages
RUN apt-get update && apt-get install -y \
    sudo \
    python3 \
    python3-venv \
    python3-pip \
    build-essential \
    libffi-dev \
    libssl-dev \
    python3-dev \
    wget \
    vim \
    pkg-config \
    cmake \
    libtool \
    git \
    libglib2.0-dev \
    zlib1g-dev \
    && rm -rf /var/lib/apt/lists/*

# Install node-gyp and prebuild-install globally
RUN npm install -g node-gyp@10.1.0 prebuild-install

# Install Grapefruit v0.12.3 and frida@16.7.0
RUN npm install -g igf@0.12.3 frida@16.7.0 koa-router@12.0.1 minimatch@9.0.5 --python=/usr/bin/python3

# Patch igf to avoid ERR_PACKAGE_PATH_NOT_EXPORTED
RUN sed -i 's/require("frida\/dist\/device")/require("frida")/' /usr/local/lib/node_modules/igf/server/dist/lib/serialize.js

# Create the frida user with a home directory
RUN useradd -m -s /bin/bash frida

# Grant frida passwordless sudo privileges
RUN echo "frida ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers.d/frida \
    && chmod 0440 /etc/sudoers.d/frida

# Switch to the frida user
USER frida
WORKDIR /home/frida

# Create and activate a Python virtual environment
RUN python3 -m venv env

# Install frida-tools 14.4.5 and objection in the virtual environment
RUN /home/frida/env/bin/pip install --no-cache-dir frida-tools==14.4.5 objection

# Create a .bashrc to automatically source the virtual environment
RUN echo "source /home/frida/env/bin/activate" >> /home/frida/.bashrc

# Set the entrypoint to launch a Bash shell
ENTRYPOINT ["/bin/bash"]
